before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

stages:
- build
- deploy
- status-report

build:
  stage: build
  tags:
  - docker
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  script:
  - tools/build.triggerBuild.sh
  artifacts:
    paths:
    - build/app/outputs/apk/development/release/*.apk

deploy:
  stage: deploy
  tags:
  - docker
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  dependencies:
  - build
  script:
  - tools/deploy.uploadToHockey.sh

status-report-success:
  stage: status-report
  tags:
  - docker
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  script:
  - post-ticket-comment -s success
  when: on_success

status-report-failure:
  stage: status-report
  tags:
  - docker
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  script:
  - post-ticket-comment -s failure
  when: on_failure
