name: ox_talk
description: OX Talk is a mail based chat app.

version: 0.5.5+405 # x.y.z+build-number

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^0.9.3
  contacts_service: ^0.2.1
  cupertino_icons: ^0.1.2
  date_format: ^1.0.6
  file_picker: ^1.3.3
  flutter_bloc: ^0.7.0
  flutter_sound: ^1.3.7
  fluttertoast: ^3.0.1
  image_cropper: ^1.0.0
  image_picker: ^0.5.0+3
  logging: ^0.11.3+2
  open_file: ^2.0.1+1
  package_info: ^0.4.0+2
  path_provider: ^0.5.0+1
  permission_handler: ^3.0.0
  rxdart: ^0.20.0 # ^0.21.0 exists but 0.20.0 is used for compatibility reasons with bloc: ^0.9.3
  shared_preferences: ^0.5.1+1
  video_player: ^0.10.0+4
  flutter_local_notifications: ^0.7.0
  firebase_messaging: ^5.0.0
  delta_chat_core:
    path: ../flutter-deltachat-core/ # Intended path outside the project context

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true