name: ox_coi
description: OX COI Messenger is a mail based chat app.

version: 0.13.0+413 # x.y.z+build-number

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  background_fetch: ^0.2.0
  bloc: ^0.14.4
  contacts_service: ^0.2.8
  crypto_keys: ^0.1.0
  cupertino_icons: ^0.1.2
  date_format: ^1.0.6
  device_info: ^0.4.0+2
  downloads_path_provider: ^0.1.0
  esys_flutter_share: ^1.0.2
  firebase_messaging: 5.1.4
  file_picker: ^1.3.8
  flutter_bloc: ^0.20.0
  flutter_html: 0.11.0
  flutter_local_notifications: ^0.7.1+3
  flutter_sound: ^1.4.8
  fluttertoast: ^3.1.0
  gettext: ^1.1.0+2
  gettext_parser: ^0.1.0+1
  http: ^0.12.0+2
  image_cropper: ^1.0.2
  image_picker: ^0.6.0+17
  logging: ^0.11.3+2
  mime: 0.9.6+3
  open_file: ^2.0.3
  package_info: ^0.4.0+5
  path_provider: ^1.1.2
  permission_handler: ^3.2.0
  pointycastle: ^1.0.1
  rxdart: ^0.22.1
  shared_preferences: ^0.5.3+4
  sprintf: ^4.0.2
  sqflite: ^1.1.6
  superellipse_shape: ^0.1.5
  transparent_image: ^1.0.0
  url_launcher: ^5.1.4
  video_player: ^0.10.1+4
  qr_flutter: ^2.1.0+55
  qr_mobile_vision: ^0.2.2
  uuid: 2.0.1
  delta_chat_core:
    path: ../flutter-deltachat-core/ # Intended path outside the project context


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.5
  mockito: ^4.1.0
  test: any
  flutter_driver:
    sdk: flutter


flutter:
  assets:
    - assets/html/
    - assets/images/
    - assets/json/
    - assets/l10n/
  uses-material-design: true

