name: ox_coi
description: OX COI Messenger is a mail based chat app.

version: 0.13.0+413 # x.y.z+build-number

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: ^1.0.6+2
  background_fetch: ^0.3.2
  bloc: ^1.0.0
  contacts_service: ^0.3.5
  crypto_keys: ^0.1.0
  cupertino_icons: ^0.1.2
  date_format: ^1.0.6
  device_info: ^0.4.1
  equatable: ^0.6.1
  firebase_messaging: ^5.1.6
  file_picker: ^1.4.2
  flutter_bloc: ^1.0.0
  flutter_html: ^0.11.0
  flutter_local_notifications: ^0.8.4
  flutter_sound: ^1.5.0
  fluttertoast: ^3.1.3
  gettext: ^1.1.0+2
  gettext_parser: ^0.1.0+1
  http: ^0.12.0+2
  image_cropper: ^1.1.0
  image_picker: ^0.6.1+8
  logging: ^0.11.3+2
  mime: ^0.9.6+3
  open_file: ^2.0.3
  package_info: ^0.4.0+9
  path_provider: ^1.4.0
  permission_handler: ^4.0.0
  pointycastle: ^1.0.1
  rxdart: ^0.22.4
  shared_preferences: ^0.5.4
  sprintf: ^4.0.2
  sqflite: ^1.1.7+1
  superellipse_shape: ^0.1.5
  transparent_image: ^1.0.0
  url_launcher: ^5.2.4
  video_player: ^0.10.2+5
  qr_flutter: ^3.0.1
  qr_mobile_vision: ^0.2.2
  uuid: ^2.0.2
  flutter_slidable: "^0.5.4"
  delta_chat_core:
    path: ../flutter-deltachat-core/ # Intended path outside the project context


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: any
  flutter_driver:
    sdk: flutter

flutter:
  assets:
    - assets/html/
    - assets/images/
    - assets/json/
    - assets/l10n/
  uses-material-design: true

