name: ox_coi
description: OX COI Messenger is a mail based chat app.

version: 0.500.1+512 # x.y.z+build-number

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: ^3.0.0+1
  background_fetch: ^0.4.0
  bloc: ^3.0.0
  contacts_service: ^0.3.10
  crypto: ^2.1.3
  crypto_keys: ^0.1.0
  cupertino_icons: ^0.1.3
  date_format: ^1.0.8
  device_info: ^0.4.1+4
  equatable: ^1.0.2
  firebase_messaging: ^6.0.9
  file_picker:
    git:
      url: git://github.com/Boehrsi/plugins_flutter_file_picker
      ref: 192_embeddingV2
  flutter_bloc: ^3.1.0
  flutter_html: ^0.11.1
  flutter_local_notifications: ^0.9.1+3
  flutter_markdown: ^0.3.2
  flutter_sound:
    git:
      url: https://github.com/open-xchange/flutter_sound
  fluttertoast: ^3.1.3
  gettext: ^1.1.0+2
  gettext_parser: ^0.1.0+1
  html2md: ^0.5.1
  http: ^0.12.0+4
  image_cropper: ^1.2.0
  image_picker: ^0.6.3+1
  logging: ^0.11.4
  mime: ^0.9.6+3
  open_file: ^3.0.0
  package_info: ^0.4.0+13
  path: ^1.6.4
  path_provider: ^1.5.1
  provider: ^4.0.4
  permission_handler: ^4.2.0+hotfix.2
  pointycastle: ^1.0.2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6
  sprintf: ^4.0.2
  sqflite: ^1.2.0
  superellipse_shape: ^0.1.5
  transparent_image: ^1.0.0
  url_launcher: ^5.4.1
  vibrate: ^0.0.4
  video_player: ^0.10.5+2
  qr_flutter: ^3.2.0
  qr_mobile_vision:
    git:
      url: https://github.com/Boehrsi/flutter_qr_mobile_vision
      ref: android-embedding-v2
  tinycolor: ^1.0.2
  uuid: ^2.0.4
  video_thumbnail:
    git:
      url: https://github.com/CihanOezkan/video_thumbnail.git
  delta_chat_core:
    path: ../flutter-deltachat-core/ # Intended path outside the project context

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: any
  flutter_driver:
    sdk: flutter

flutter:
  assets:
    - assets/customer/
    - assets/html/
    - assets/images/
    - assets/json/
    - assets/l10n/
  uses-material-design: true

